language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t dochiro94/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dochiro94/react-test npm test

after_success:
  - docker build -t dochiro94/multi-client ./client # don't specifiy the docker file b/c it use the default
  - docker build -t dochiro94/multi-nginx ./nginx
  - docker build -t dochiro94/multi-server ./server
  - docker build -t dochiro94/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push dochiro94/multi-client
  - docker push dochiro94/multi-nginx
  - docker push dochiro94/multi-server
  - docker push dochiro94/multi-worker
  
deploy:
  edge: true
  provider: elasticbeanstalk
  region: "eu-south-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-south-1-759315199516"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"